services:
  # Python scraper
  scraper:
    container_name: Scraper
    build: ./scraper
    depends_on:
      - mongo
      - tor
  # Express application
  backend:
    container_name: Express
    hostname: backend
    build:
      context: ./backend
      target: development
    command: npm run dev-watch
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  # React application
  frontend:
    container_name: React
    hostname: frontend
    build:
      context: ./frontend
      target: development
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
  # MongoDB Database
  mongo:
    image: mongo
    container_name: Mongo
    hostname: mongo
    ports:
      - 27017:27017
  # Tor browser
  tor:
    image: dperson/torproxy
    container_name: Tor
    hostname: tor
    ports:
      - 9050:9050
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: RabbitMQ
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/Documents/data/rabbitmq/data/:/var/lib/rabbitmq
      - ~/Documents/data/rabbitmq/log/:/var/log/rabbitmq
