services:
  # MongoDB Database
  mongo:
    container_name: Mongo
    hostname: mongo
    image: mongo
    ports:
      - 27017:27017
  # Tor browser
  tor:
    container_name: Tor
    hostname: tor
    image: dperson/torproxy
    ports:
      - 9050:9050
  # Python scraper
  scraper:
    container_name: Scraper
    build: ./scraper
    depends_on:
      - mongo
      - tor
  # Express application
  backend:
    container_name: Express
    hostname: backend
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  # React application
  frontend:
    container_name: React
    hostname: frontend
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
